apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
    component: web-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  replicas: 5 # You can adjust the number of replicas as needed
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # You can specify a different Nginx image version
        ports:
        - containerPort: 80